{% set name = "shakenbreak" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0a4f7b495683532441ea7a8ff26fc42f4de9901baabc8ed8f1a35e045fac0810

build:
  noarch: python
  number: 0
  entry_points:
    - snb = shakenbreak.cli:snb
    - snb-generate = shakenbreak.cli:generate
    - snb-generate_all = shakenbreak.cli:generate_all
    - snb-run = shakenbreak.cli:run
    - snb-parse = shakenbreak.cli:parse
    - snb-analyse = shakenbreak.cli:analyse
    - snb-plot = shakenbreak.cli:plot
    - snb-regenerate = shakenbreak.cli:regenerate
    - snb-groundstate = shakenbreak.cli:groundstate
    - snb-mag = shakenbreak.cli:mag
    - shakenbreak = shakenbreak.cli:snb
    - shakenbreak-generate = shakenbreak.cli:generate
    - shakenbreak-generate_all = shakenbreak.cli:generate_all
    - shakenbreak-run = shakenbreak.cli:run
    - shakenbreak-parse = shakenbreak.cli:parse
    - shakenbreak-analyse = shakenbreak.cli:analyse
    - shakenbreak-plot = shakenbreak.cli:plot
    - shakenbreak-regenerate = shakenbreak.cli:regenerate
    - shakenbreak-groundstate = shakenbreak.cli:groundstate
    - shakenbreak-mag = shakenbreak.cli:mag
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8,<3.11
  run:
    - ase
    - click >8.0
    - hiphive
    - importlib_metadata
    - matplotlib-base
    - monty
    - numpy >=1.21.2,<1.24
    - pandas >=1.1.0
    - pymatgen >=2022.10.22
    - pymatgen-analysis-defects >=2022.10.28
    - python >=3.8,<3.11
    - seaborn

test:
  imports:
    - shakenbreak
    - tests
  commands:
    - snb --help
    - snb-generate --help
    - snb-generate_all --help
    - snb-run --help
    - snb-parse --help
    - snb-analyse --help
    - snb-plot --help
    - snb-regenerate --help
    - snb-groundstate --help
    - snb-mag --help
    - shakenbreak --help
    - shakenbreak-generate --help
    - shakenbreak-generate_all --help
    - shakenbreak-run --help
    - shakenbreak-parse --help
    - shakenbreak-analyse --help
    - shakenbreak-plot --help
    - shakenbreak-regenerate --help
    - shakenbreak-groundstate --help
    - shakenbreak-mag --help

about:
  home: https://github.com/SMTG-UCL/ShakeNBreak
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Package to generate and analyse distorted defect structures, in order to identify ground-state and metastable defect configurations.
  doc_url: https://shakenbreak.readthedocs.io/en/latest/
  dev_url: https://github.com/SMTG-UCL/ShakeNBreak

extra:
  recipe-maintainers:
    - kavanase
    - ireaml
